services:
  backend:
    build:
      context: ${BACKEND_PATH}
    ports:
      - "${BACKEND_PORT}:8000"
    env_file:
      - ${BACKEND_PATH}/.env
    volumes:
      - ${BACKEND_PATH}:/app
      - ${BACKEND_PATH}/mounted_data:/mnt/data
    restart: always

  redis:
    image: redis:6.0
    ports:
      - "6379:6379"

  frontend:
    build:
      context: ${FRONTEND_PATH}
    ports:
      - "${FRONTEND_PORT}:80"
    env_file:
      - ${FRONTEND_PATH}/.env
    depends_on:
      - backend
    restart: always