services:
  backend:
    build:
      context: ./backend
    ports:
      - "${BACKEND_PORT}:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    restart: always

  redis:
    image: redis:6.0
    ports:
      - "6379:6379"

  frontend:
    build:
      context: ./frontend
    ports:
      - "${FRONTEND_PORT}:80"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    restart: always