services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:8000"
    environment:
      NEO4J_URL: ${NEO4J_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      REDIS_URL: ${REDIS_URL}
      DEBUG: ${DEBUG}
      ALLOWED_CORS_ORIGINS: ${ALLOWED_CORS_ORIGINS}
    volumes:
      - .:/app
      - ./mounted_data:/mnt/data
    command: >
      uvicorn main:app
      --host 0.0.0.0
      --port 8000

  redis:
    image: redis:6.0
    ports:
      - "6379:6379"